[package]
name = "trayicon-winit-example"
version = "0.0.1"
authors = ["Jari Otto Oskari Pennanen"]
edition = "2018"
publish = false

[dependencies]
winit = "0.24"
trayicon = { path = "../../", features = ["winit"] }
